/*
 * 机构数据分析
 */
package gov.gdgs.zs.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

@Repository
public class JGSJFXDao extends BaseDao {
	
	/*
	 * 行业学历数据分析
	 */
	public Map<String, Object> getHyxlsjfxb(int page, int pageSize,
			HashMap<String, Object> map){
		StringBuffer sb = new StringBuffer();
		sb.append(" select SQL_CALC_FOUND_ROWS @rownum:=@rownum+1,t.*");
		sb.append("  from(select date_format(now(),'%Y') as nd, ");
		sb.append("  cs.ID, ");
		sb.append("        cs.PARENT_ID, ");
		sb.append("        cs.mc, ");
		sb.append("        ifnull((select count(id) from zs_ryjbxx where yxbz = '1'),0) zrs,  ");
		sb.append("        ifnull((select count(id) ");
		sb.append("           from zs_ryjbxx ");
		sb.append("          where yxbz = '1' ");
		sb.append("            and xl_dm in ('4', '5')),0) yjs_zrs,  ");
		sb.append("       ifnull( (select count(id) ");
		sb.append("           from zs_ryjbxx ");
		sb.append("          where yxbz = '1' ");
		sb.append("            and xl_dm = '1') ,0)bk_zrs,  ");
		sb.append("       ifnull( (select count(id) ");
		sb.append("           from zs_ryjbxx ");
		sb.append("          where yxbz = '1' ");
		sb.append("            and xl_dm = '2'),0) dz_zrs,  ");
		sb.append("       ifnull( (select count(id) ");
		sb.append("           from zs_ryjbxx ");
		sb.append("          where yxbz = '1' ");
		sb.append("            and xl_dm in ('6', '3')),0) gz_zrs,  ");
		sb.append("         ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_zysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1'),0) zy_zrs,  ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_zysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm in ('4', '5')),0) zy_yjs_zrs,  ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_zysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm = '1'),0) zy_bk_zrs, ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_zysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm = '2'),0) zy_dz_zrs, ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_zysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm in ('6', '3')),0) zy_gz_zrs,  ");
		sb.append("         ");
		sb.append("       ifnull( (select count(zy.id) ");
		sb.append("           from zs_fzysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1'),0) fzy_zrs, ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_fzysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm in ('4', '5')) ,0)fzy_yjs_zrs,  ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_fzysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm = '1'),0) fzy_bk_zrs,");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_fzysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm = '2'),0) fzy_dz_zrs, ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_fzysws zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm in ('6', '3')) ,0)fzy_gz_zrs,");
		sb.append("         ");
		sb.append("       ifnull( (select count(zy.id) ");
		sb.append("           from zs_cyry zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1') ,0)cy_zrs,");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_cyry zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm in ('4', '5')),0) cy_yjs_zrs,  ");
		sb.append("        ifnull((select count(zy.id) ");
		sb.append("           from zs_cyry zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm = '1'),0) cy_bk_zrs, ");
		sb.append("       ifnull( (select count(zy.id) ");
		sb.append("           from zs_cyry zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm = '2'),0) cy_dz_zrs,    ");
		sb.append("       ifnull( (select count(zy.id) ");
		sb.append("           from zs_cyry zy, zs_ryjbxx jb ");
		sb.append("          where zy.ry_id = jb.id ");
		sb.append("            and jb.yxbz = '1' ");
		sb.append("            and jb.xl_dm in ('6', '3')),0) cy_gz_zrs      ");
		sb.append("   from dm_cs cs ");
		sb.append("  where cs.parent_id is null ");
		sb.append(" union all ");
		sb.append("  ");
		sb.append(" select date_format(now(),'%Y') as nd, ");
		sb.append("  cs.ID, ");
		
		sb.append("        cs.PARENT_ID, ");
		sb.append("        cs.mc, ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0'  is not null then ");
		sb.append("            1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null then ");
		sb.append("           1 ");
		sb.append("          else 0 ");
		sb.append("        end),0) zrs, ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm in ('4', '5') then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and ");
		sb.append("               xl_dm in ('4', '5') then ");
		sb.append("            1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '1' then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '1' then ");
		sb.append("           1 ");
		sb.append("          else 0 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '2' then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '2' then ");
		sb.append("           1 ");
		sb.append("          else 0 ");
		sb.append("        end),0), ");
		sb.append("       ifnull( sum(case ");
		sb.append("          when parent_id = '0' and xl_dm in ('6', '3') then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and ");
		sb.append("               xl_dm in ('6', '3') then ");
		sb.append("           1 ");
		sb.append("          else 0 ");
		sb.append("        end),0), ");
		sb.append("         ");
		
		sb.append("       ifnull(sum( case ");
		sb.append("          when parent_id = '0' and id_2 is not null then ");
		sb.append("          1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and id_2 is not null then ");
		sb.append("           1 ");
		sb.append("        end),0) zrs, ");
		sb.append("       ifnull(sum( case ");
		sb.append("          when parent_id = '0' and id_2 is not null and xl_dm in ('4', '5') then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and ");
		sb.append("               xl_dm in ('4', '5') and id_2 is not null then ");
		sb.append("          1 ");
		sb.append("          else 0 ");
		sb.append("        end),0), ");
		sb.append("       ifnull(sum( case ");
		sb.append("          when parent_id = '0' and xl_dm = '1' and id_2 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '1' and id_2 is not null then ");
		sb.append("           1 ");
		sb.append("         else 0 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '2' and id_2 is not null then ");
		sb.append("          1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '2' and id_2 is not null then ");
		sb.append("          1 ");
		sb.append("          else 0 ");
		sb.append("        end),0), ");
		sb.append("       ifnull( sum(case ");
		sb.append("          when parent_id = '0' and xl_dm in ('6', '3') and id_2 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null  and id_2 is not null and ");
		sb.append("               xl_dm in ('6', '3') then ");
		sb.append("          1 ");
		sb.append("          else 0 ");
		sb.append("        end),0), ");
		sb.append("         ");
		sb.append("       ifnull( sum(case ");
		sb.append("          when parent_id = '0' and id_3 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and id_3 is not null then ");
		sb.append("          1 ");
		sb.append("          else 0 ");
		sb.append("        end),0) zrs, ");
		sb.append("       ifnull( sum(case ");
		sb.append("          when parent_id = '0' and xl_dm in ('4', '5') and id_3 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and id_3 is not null and ");
		sb.append("               xl_dm in ('4', '5') then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("       ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '1' and id_3 is not null then ");
		sb.append("          1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '1' and id_3 is not null then ");
		sb.append("           1 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '2' and id_3 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '2'  and id_3 is not null then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm in ('6', '3') and id_3 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and id_3 is not null and ");
		sb.append("               xl_dm in ('6', '3') then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("         ");
		sb.append("        ");
		sb.append("       ifnull( sum(case ");
		sb.append("          when parent_id = '0' and id_4 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and  id_4 is not null then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end) ,0)zrs, ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm in ('4', '5') and  id_4 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and id_4 is not null and ");
		sb.append("               xl_dm in ('4', '5') then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '1'and  id_4 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and  id_4 is not null and xl_dm = '1' then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("        ifnull(sum(case ");
		sb.append("          when parent_id = '0' and xl_dm = '2' and  id_4 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and xl_dm = '2' and  id_4 is not null then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0), ");
		sb.append("       ifnull(sum( case ");
		sb.append("          when parent_id = '0' and xl_dm in ('6', '3') and  id_4 is not null then ");
		sb.append("           1 ");
		sb.append("          when parent_id <> '0' and parent_id is not null and  id_4 is not null and ");
		sb.append("               xl_dm in ('6', '3') then ");
		sb.append("           1 ");
		sb.append("           else 0 ");
		sb.append("        end),0) ");
		sb.append("  ");
		sb.append("   from (select jb.id    id_1, ");
		sb.append("                zy.id    id_2, ");
		sb.append("                fz.id    id_3, ");
		sb.append("                cy.id    id_4, ");
		sb.append("                jb.xl_dm, ");
		sb.append("                jb.cs_dm ");
		sb.append("           from zs_ryjbxx jb ");
		sb.append("           left join zs_zysws zy ");
		sb.append("             on jb.id = zy.ry_id ");
		sb.append("           left join zs_fzysws fz ");
		sb.append("             on jb.id = fz.ry_id ");
		sb.append("           left join zs_cyry cy ");
		sb.append("             on jb.id = cy.ry_id ");
		sb.append("          where jb.yxbz = '1') jg ");
		sb.append("  right join dm_cs cs ");
		sb.append("     on jg.CS_DM = cs.id ");
		sb.append("  where cs.parent_id is not null ");
		sb.append("  group by cs.ID, cs.PARENT_ID, cs.mc )as t");
		sb.append("    ");
	//StringBuffer sqlCount = new StringBuffer(" select count(*) from( ");
	//sqlCount.append(sb).append(" )t ");
	List<Map<String, Object>> ls=jdbcTemplate.queryForList(sb.toString());
	//int total = this.jdbcTemplate.queryForObject(sqlCount.toString(),new Object[]{nd,nd}, int.class);
	
   int total = this.jdbcTemplate.queryForObject("SELECT FOUND_ROWS()", Integer.class);
	Map<String, Object> obj = new HashMap<String, Object>();
	
	
	obj.put("data", ls);
	obj.put("total", total);
	//obj.put("pageSize", 1);
	//obj.put("current", 1);

	return obj;
	
	}
/*
 * 资金规模数据分析
 */
	
	public Map<String, Object> getZjgmsjfxb(int page, int pageSize,
			HashMap<String, Object> map){
		StringBuffer sb = new StringBuffer();
		sb.append(" select SQL_CALC_FOUND_ROWS @rownum:=@rownum+1,t2.*");
		sb.append("   from( select *, ");
		sb.append("        round(fhzcgd_yx * 100 / zjgs, 2) fhzcgd_yx_bl, ");
		sb.append("        round(fhzcgd_hh * 100 / zjgs, 2) fhzcgd__hh_bl, ");
		sb.append("        round(fhzcgd_fs * 100 / zjgs, 2) fhzcgd_fs_bl, ");
		sb.append("        round(bfhzcgd_yx * 100 / zjgs, 2) bfhzcgd_yx_bl, ");
		sb.append("        round(bfhzcgd_hh * 100 / zjgs, 2) bfhzcgd__hh_bl, ");
		sb.append("        round(bfhzcgd_fs * 100 / zjgs, 2) bfhzcgd_fs_bl ");
		sb.append("   from (select cs.ID, ");
		sb.append(" date_format(now(),'%Y') as nd,");
		sb.append("                cs.PARENT_ID, ");
		sb.append("                cs.mc, ");
		sb.append("                ifnull(sum(case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(zczj) from zs_jg where yxbz = '1') ");
		sb.append("                  when parent_id = '0' then ");
		sb.append("                  zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null then ");
		sb.append("                  zczj ");
		sb.append("                end),0) zjgs,  ");
		sb.append("                 ");
		sb.append("               ifnull( sum(case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(jg.zczj) ");
		sb.append("                      from zs_jg jg ");
		sb.append("                      left join zs_jgyjxxb yj ");
		sb.append("                        on jg.id = yj.id ");
		sb.append("                     where yxbz = '1' ");
		sb.append("                       and flag = '1' ");
		sb.append("                       and jgxz_dm = '2') ");
		sb.append("                  when parent_id = '0' and flag = '1' and jgxz_dm = '2' then ");
		sb.append("                   zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null and ");
		sb.append("                       flag = '1' and jgxz_dm = '2' then ");
		sb.append("                   zczj ");
		sb.append("                end),0) fhzcgd_yx,  ");
		sb.append("                 ");
		sb.append("               ifnull( sum(case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(jg.zczj) ");
		sb.append("                      from zs_jg jg ");
		sb.append("                      left join zs_jgyjxxb yj ");
		sb.append("                        on jg.id = yj.id ");
		sb.append("                     where yxbz = '1' ");
		sb.append("                       and flag = '1' ");
		sb.append("                       and jgxz_dm = '1') ");
		sb.append("                  when parent_id = '0' and flag = '1' and jgxz_dm = '1' then ");
		sb.append("                   zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null and ");
		sb.append("                       flag = '1' and jgxz_dm = '1' then ");
		sb.append("                   zczj ");
		sb.append("                end) ,0)fhzcgd_hh,  ");
		sb.append("                 ");
		sb.append("               ifnull( sum(case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(jg.zczj) ");
		sb.append("                      from zs_jg jg ");
		sb.append("                      left join zs_jgyjxxb yj ");
		sb.append("                        on jg.id = yj.id ");
		sb.append("                     where yxbz = '1' ");
		sb.append("                       and flag = '1' ");
		sb.append("                       and jgxz_dm = '3') ");
		sb.append("                  when parent_id = '0' and flag = '1' and jgxz_dm = '3' then ");
		sb.append("                   zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null and ");
		sb.append("                       flag = '1' and jgxz_dm = '3' then ");
		sb.append("                   zczj ");
		sb.append("                end) ,0)fhzcgd_fs,  ");
		sb.append("                 ");
		sb.append("               ifnull(sum( case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(jg.zczj) ");
		sb.append("                      from zs_jg jg ");
		sb.append("                      left join zs_jgyjxxb yj ");
		sb.append("                        on jg.id = yj.id ");
		sb.append("                     where yxbz = '1' ");
		sb.append("                       and flag = '0' ");
		sb.append("                       and jgxz_dm = '2') ");
		sb.append("                  when parent_id = '0' and flag = '0' and jgxz_dm = '2' then ");
		sb.append("                   zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null and ");
		sb.append("                       flag = '0' and jgxz_dm = '2' then ");
		sb.append("                   zczj ");
		sb.append("                end),0) bfhzcgd_yx,  ");
		sb.append("                 ");
		sb.append("               ifnull( sum(case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(jg.zczj) ");
		sb.append("                      from zs_jg jg ");
		sb.append("                      left join zs_jgyjxxb yj ");
		sb.append("                        on jg.id = yj.id ");
		sb.append("                     where yxbz = '1' ");
		sb.append("                       and flag = '0' ");
		sb.append("                       and jgxz_dm = '1') ");
		sb.append("                  when parent_id = '0' and flag = '0' and jgxz_dm = '1' then ");
		sb.append("                   zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null and ");
		sb.append("                       flag = '0' and jgxz_dm = '1' then ");
		sb.append("                   zczj ");
		sb.append("                end),0) bfhzcgd_hh,  ");
		sb.append("                 ");
		sb.append("               ifnull( sum(case ");
		sb.append("                  when parent_id is null then ");
		sb.append("                   (select sum(jg.zczj) ");
		sb.append("                      from zs_jg jg ");
		sb.append("                      left join zs_jgyjxxb yj ");
		sb.append("                        on jg.id = yj.id ");
		sb.append("                     where yxbz = '1' ");
		sb.append("                       and flag = '0' ");
		sb.append("                       and jgxz_dm = '3') ");
		sb.append("                  when parent_id = '0' and flag = '0' and jgxz_dm = '3' then ");
		sb.append("                   zczj ");
		sb.append("                  when parent_id <> '0' and parent_id is not null and ");
		sb.append("                       flag = '0' and jgxz_dm = '3' then ");
		sb.append("                   zczj ");
		sb.append("                end),0) bfhzcgd_fs ");
		sb.append("           from (select jg.ID, jg.JGXZ_DM, yj.FLAG, jg.cs_dm, jg.zczj ");
		sb.append("                   from zs_jg jg ");
		sb.append("                   left join zs_jgyjxxb yj ");
		sb.append("                     on jg.id = yj.id ");
		sb.append("                  where jg.yxbz = '1') jg ");
		sb.append("          right join dm_cs cs ");
		sb.append("             on jg.CS_DM = cs.id ");
		sb.append("          ");
		sb.append("          group by cs.ID, cs.PARENT_ID, cs.mc) as t) as t2");
		sb.append("    ");
	//StringBuffer sqlCount = new StringBuffer(" select count(*) from( ");
	//sqlCount.append(sb).append(" )t ");
	List<Map<String, Object>> ls=jdbcTemplate.queryForList(sb.toString());
	int total = this.jdbcTemplate.queryForObject("SELECT FOUND_ROWS()", int.class);
	
   //int total = this.jdbcTemplate.queryForObject(sqlCount.toString(), Integer.class);
	Map<String, Object> obj = new HashMap<String, Object>();
	
	
	obj.put("data", ls);
	obj.put("total", total);
	//obj.put("pageSize", 1);
	//obj.put("current", 1);

	return obj;
	
	}
	
	
	
}

