package gov.gdgs.zs.dao;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class NDJZQKTJDao extends BaseDao {
	
	
	public Map<String, Object> ndjzqktj(int nd){
	StringBuffer sb=new StringBuffer();
	sb.append("  select '汇算清缴鉴证业务' xmlx, ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(HSQJJE_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(HSQJJE_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(HSQJJE_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(HSQJJE_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(HSQJJE_JE), 0) - ifnull(sum(HSQJJE_JE0), 0) je_zj, ");
	sb.append("                ifnull(sum(HSQJJE_HS), 0) - ifnull(sum(HSQJJE_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           ");
	sb.append("           ");
	sb.append(" union all ");
	sb.append(" select '弥补亏损鉴证业务金额', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(MBKSJE_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(MBKSJE_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(MBKSJE_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(MBKSJE_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(MBKSJE_JE), 0) - ifnull(sum(MBKSJE_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(MBKSJE_HS), 0) - ifnull(sum(MBKSJE_HS0),0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           ");
	sb.append("          union all ");
	sb.append(" select '企业财产损失税前扣除鉴证业务金额', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(CCSSKC_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(CCSSKC_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(CCSSKC_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(CCSSKC_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(CCSSKC_JE), 0) - ifnull(sum(CCSSKC_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(CCSSKC_HS), 0) - ifnull(sum(CCSSKC_HS0),0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("  union all ");
	sb.append(" select '其他鉴证业务金额', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(QTJZ_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(QTJZ_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(QTJZ_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(QTJZ_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(QTJZ_JE), 0) - ifnull(sum(QTJZ_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(QTJZ_HS), 0) - ifnull(sum(QTJZ_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '其他鉴证业务', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(QTJZ_JE2), 0) je_bn, ");
	sb.append("                ifnull(sum(QTJZ_HS2), 0) hs_bn, ");
	sb.append("                ifnull(sum(QTJZ_JE20), 0) je_qn, ");
	sb.append("                ifnull(sum(QTJZ_HS20), 0) hs_qn, ");
	sb.append("                ifnull(sum(QTJZ_JE2), 0) - ifnull(sum(QTJZ_JE20),0) je_zj, ");
	sb.append("                ifnull(sum(QTJZ_HS2), 0) - ifnull(sum(QTJZ_HS20), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '其他鉴证业务', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(QTJZ_JE3), 0) je_bn, ");
	sb.append("                ifnull(sum(QTJZ_HS3), 0) hs_bn, ");
	sb.append("                ifnull(sum(QTJZ_JE30), 0) je_qn, ");
	sb.append("                ifnull(sum(QTJZ_HS30), 0) hs_qn, ");
	sb.append("                ifnull(sum(QTJZ_JE3), 0) - ifnull(sum(QTJZ_JE30),0) je_zj, ");
	sb.append("                ifnull(sum(QTJZ_HS3), 0) - ifnull(sum(QTJZ_HS30), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '土地增值税清算签证业务', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(TDZZSQSJZ_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(TDZZSQSJZ_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(TDZZSQSJZ_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(TDZZSQSJZ_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(TDZZSQSJZ_JE), 0) - ifnull(sum(TDZZSQSJZ_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(TDZZSQSJZ_HS), 0) - ifnull(sum(TDZZSQSJZ_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '高新技术企业认定签证业务', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(GXJSQYRDQZYW_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(GXJSQYRDQZYW_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(GXJSQYRDQZYW_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(GXJSQYRDQZYW_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(GXJSQYRDQZYW_JE), 0) - ifnull(sum(GXJSQYRDQZYW_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(GXJSQYRDQZYW_HS), 0) - ifnull(sum(GXJSQYRDQZYW_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '企业注销税务登记税款清算签证业务', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(QYZXSWDESKJSJZYW_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(QYZXSWDESKJSJZYW_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(QYZXSWDESKJSJZYW_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(QYZXSWDESKJSJZYW_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(QYZXSWDESKJSJZYW_JE), 0) - ifnull(sum(QYZXSWDESKJSJZYW_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(QYZXSWDESKJSJZYW_HS), 0) - ifnull(sum(QYZXSWDESKJSJZYW_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '研发费加计扣除签证业务', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(YFFJJKCJZYW_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(YFFJJKCJZYW_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(YFFJJKCJZYW_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(YFFJJKCJZYW_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(YFFJJKCJZYW_JE), 0) - ifnull(sum(YFFJJKCJZYW_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(YFFJJKCJZYW_HS), 0) - ifnull(sum(YFFJJKCJZYW_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	sb.append("           union all ");
	sb.append(" select '其他户数', ");
	sb.append("        hs_qn, ");
	sb.append("        je_qn, ");
	sb.append("        hs_bn, ");
	sb.append("        je_bn, ");
	sb.append("        hs_zj, ");
	sb.append("        je_zj, ");
	sb.append("        round(hs_zj * 100 / (case ");
	sb.append("                when hs_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 hs_bn ");
	sb.append("              end), ");
	sb.append("              2) hs_bl, ");
	sb.append("        round(je_zj * 100 / (case ");
	sb.append("                when je_bn = 0 then ");
	sb.append("                 null ");
	sb.append("                else ");
	sb.append("                 je_bn ");
	sb.append("              end), ");
	sb.append("              2) je_bl ");
	sb.append("   from (select ifnull(sum(QT_JE), 0) je_bn, ");
	sb.append("                ifnull(sum(QT_HS), 0) hs_bn, ");
	sb.append("                ifnull(sum(QT_JE0), 0) je_qn, ");
	sb.append("                ifnull(sum(QT_HS0), 0) hs_qn, ");
	sb.append("                ifnull(sum(QT_JE), 0) - ifnull(sum(QT_JE0),0) je_zj, ");
	sb.append("                ifnull(sum(QT_HS), 0) - ifnull(sum(QT_HS0), 0) hs_zj ");
	sb.append("           from zs_sdsb_jzywqktjb ");
	sb.append("          where nd = ?) a ");
	
	List<Map<String, Object>> ls=jdbcTemplate.queryForList(sb.toString(),new Object[]{nd,nd,nd,nd,nd,nd,nd,nd,nd,nd,nd});
	Map<String, Object> obj = new HashMap<String, Object>();
	obj.put("data", ls);
	obj.put("total", 1);
	//obj.put("pageSize", 1);
	//obj.put("current", 1);

	return obj;
	
	}

	
}

